### ISSUE TITLE
Nupic?

### ISSUE THREAD

**Issue by pranv** [aymericdamien/TopDeepLearning#4]
I think neither the Numenta guys nor the DL guys would agree that they should be on this list?

**Comment by rhyolight** [comment]
NuPIC is an implementation of [Hierarchical Temporal Memory](https://github.com/numenta/nupic/wiki/Hierarchical-Temporal-Memory-Theory), which is not Deep Learning. HTM is an attempt to understand how intelligence is implemented in the mammalian neocortex and implement those principles in software.

**Comment by aymericdamien** [comment]
Yes, true, I will remove it
